import "./globals.css";
import type { Metadata } from "next";
import { Providers } from "./providers";
import { fonts } from "./fonts";
import { ColorModeScript } from "@chakra-ui/react";
import { theme } from "./theme";
import { Navbar } from "@/components/layouts/Navbar";

export const metadata: Metadata = {
  title: "Tighcoin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${fonts.dongle.variable} ${fonts.pacifico.variable}`}
    >
      <body suppressHydrationWarning={true}>
        <Providers>
          <Navbar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
